# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao7xSM4TJH-qDZvDpg-R0tuuB0ApwsVI
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import fashion_mnist
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV


(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()


x_train = x_train.reshape(-1, 28*28).astype('float32') / 255.0
x_test = x_test.reshape(-1, 28*28).astype('float32') / 255.0

# استانداردسازی داده‌ها
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# تنظیمات GridSearchCV برای جستجوی بهترین پارامترها
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'poly', 'rbf'],
    'degree': [3, 4],
    'gamma': ['scale', 'auto']
}


svm = SVC()


grid_search = GridSearchCV(svm, param_grid, cv=3, verbose=2, n_jobs=-1)
grid_search.fit(x_train, y_train)

# بهترین پارامترها
best_params = grid_search.best_params_
print(f"Best Parameters: {best_params}")


best_svm = grid_search.best_estimator_
y_pred_svm = best_svm.predict(x_test)
svm_accuracy = accuracy_score(y_test, y_pred_svm)
print(f"SVM Accuracy: {svm_accuracy}")